name: Auto-merge Dependabot updates

on:
  pull_request:
    types:
      - opened
      - labeled
      - synchronize

jobs:
  automerge:
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - name: Auto-merge Dependabot PR
        uses: "peter-evans/enable-pull-request-automerge@v3"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          merge-method: squash
